rootProject.name = "trixnity"
include("trixnity-core")
include("trixnity-olm")
include("trixnity-client")
include("trixnity-client-sqldelight")
include("trixnity-client-api")
include("trixnity-appservice")
include("integration-tests")
include("examples")
include("examples:api-client-multiplatform-ping")
include("examples:client-multiplatform-ping")