#! /usr/bin/env bash

# Update api files generated by the Kotlin ABI checker
# Input: report.zip downloaded from the checkAbi CI job

set -euo pipefail

if [[ $# -ne 1 ]]; then
  echo "Usage: $0 <report.zip>"
  exit 1
fi

ZIP_FILE="$1"
PROJECT_ROOT="$(pwd)"

unzip -Z1 "$ZIP_FILE" | grep "\.api$" | while read -r ZIP_PATH; do
  if [[ "$ZIP_PATH" != */build/kotlin/abi-legacy/* ]]; then continue; fi

  MODULE_PATH="${ZIP_PATH%%/build/kotlin/abi-legacy/*}"
  REL_PATH="${ZIP_PATH#*/build/kotlin/abi-legacy/}" # jvm, android or empty

  DEST_PATH="$PROJECT_ROOT/$MODULE_PATH/api/$REL_PATH"

  mkdir -p "$(dirname "$DEST_PATH")"
  unzip -p "$ZIP_FILE" "$ZIP_PATH" > "$DEST_PATH"
done
