version: "3.3"

services:
  synapse:
    image: "matrixdotorg/synapse:latest"
    container_name: "synapse"
    volumes:
      - "./data:/data"
    environment:
      VIRTUAL_HOST: "localhost"
      VIRTUAL_PORT: 8008
      SYNAPSE_SERVER_NAME: "localhost"
      SYNAPSE_REPORT_STATS: "no"
      GUI: 1000
      UID: 1000
    ports:
      - 8008:8008